#!/bin/bash
set -euxo pipefail
cargo build --release --bin fixbn3
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaBrother.sav ../tango/tango/src/game/bn3/save/aqua_team_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaBug.sav ../tango/tango/src/game/bn3/save/aqua_bug_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaCustom.sav ../tango/tango/src/game/bn3/save/aqua_custom_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaGround.sav ../tango/tango/src/game/bn3/save/aqua_ground_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaGuts.sav ../tango/tango/src/game/bn3/save/aqua_guts_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_AquaShield.sav ../tango/tango/src/game/bn3/save/aqua_shield_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecBrother.sav ../tango/tango/src/game/bn3/save/elec_team_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecBug.sav ../tango/tango/src/game/bn3/save/elec_bug_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecCustom.sav ../tango/tango/src/game/bn3/save/elec_custom_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecGround.sav ../tango/tango/src/game/bn3/save/elec_ground_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecGuts.sav ../tango/tango/src/game/bn3/save/elec_guts_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_ElecShield.sav ../tango/tango/src/game/bn3/save/elec_shield_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatBrother.sav ../tango/tango/src/game/bn3/save/heat_team_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatBug.sav ../tango/tango/src/game/bn3/save/heat_bug_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatCustom.sav ../tango/tango/src/game/bn3/save/heat_custom_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatGround.sav ../tango/tango/src/game/bn3/save/heat_ground_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatGuts.sav ../tango/tango/src/game/bn3/save/heat_guts_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_HeatShield.sav ../tango/tango/src/game/bn3/save/heat_shield_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodBrother.sav ../tango/tango/src/game/bn3/save/wood_team_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodBug.sav ../tango/tango/src/game/bn3/save/wood_bug_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodCustom.sav ../tango/tango/src/game/bn3/save/wood_custom_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodGround.sav ../tango/tango/src/game/bn3/save/wood_ground_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodGuts.sav ../tango/tango/src/game/bn3/save/wood_guts_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_WT_WoodShield.sav ../tango/tango/src/game/bn3/save/wood_shield_white_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaBrother.sav ../tango/tango/src/game/bn3/save/aqua_team_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaBug.sav ../tango/tango/src/game/bn3/save/aqua_bug_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaCustom.sav ../tango/tango/src/game/bn3/save/aqua_custom_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaGuts.sav ../tango/tango/src/game/bn3/save/aqua_guts_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaShadow.sav ../tango/tango/src/game/bn3/save/aqua_shadow_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_AquaShield.sav ../tango/tango/src/game/bn3/save/aqua_shield_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecBrother.sav ../tango/tango/src/game/bn3/save/elec_team_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecBug.sav ../tango/tango/src/game/bn3/save/elec_bug_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecCustom.sav ../tango/tango/src/game/bn3/save/elec_custom_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecGuts.sav ../tango/tango/src/game/bn3/save/elec_guts_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecShadow.sav ../tango/tango/src/game/bn3/save/elec_shadow_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_ElecShield.sav ../tango/tango/src/game/bn3/save/elec_shield_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatBrother.sav ../tango/tango/src/game/bn3/save/heat_team_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatBug.sav ../tango/tango/src/game/bn3/save/heat_bug_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatCustom.sav ../tango/tango/src/game/bn3/save/heat_custom_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatGuts.sav ../tango/tango/src/game/bn3/save/heat_guts_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatShadow.sav ../tango/tango/src/game/bn3/save/heat_shadow_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_HeatShield.sav ../tango/tango/src/game/bn3/save/heat_shield_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodBrother.sav ../tango/tango/src/game/bn3/save/wood_team_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodBug.sav ../tango/tango/src/game/bn3/save/wood_bug_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodCustom.sav ../tango/tango/src/game/bn3/save/wood_custom_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodGuts.sav ../tango/tango/src/game/bn3/save/wood_guts_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodShadow.sav ../tango/tango/src/game/bn3/save/wood_shadow_blue_any.raw
target/release/fixbn3 data/*/ROCK_EXE3_BK_WoodShield.sav ../tango/tango/src/game/bn3/save/wood_shield_blue_any.raw
